install: export CXX="g++-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5 

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
# Build steps
script:
  - make clean
  - make all
 
